language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '8'
  - '7'
  - '6'
  - '10'
before_script:
  - npm prune
script:
  - npm run prepublishOnly
after_success:

branches:
  except:
    - /^v\d+\.\d+\.\d+$/